passportServiceApi:
  common:
      protocol: http
      host: localhost
      port: 9090
  entry:
      passport: /passports
      save: /save
      update: /update
      delete: /delete
      find: /find
      findBySerial: ${passportServiceApi.entry.find}
      unavailable: /unavailable
      findReplaceable: /find-replaceable
